### ISSUE TITLE
Use workerman to create Htpp service in docker swarm, process death cannot trigger container restart

### ISSUE THREAD

**Issue by Iamzz-cn** [walkor/Workerman#560]
As the title
docker-compose.yml
```
version: "3"
services:
  http:
...
    deploy:
      replicas: 2
      restart_policy:
        condition: always
...
    networks:
      - test
networks:
  test:
```
Dockerfile
```
...
CMD ["php","-d","memory_limit=512M","start.php","start"]
```
I don't know if workerman has a container-specific run mode
